spring:
    pid:
        file: bserver.pid
    mvc:    
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6378